import os
import ollama
import random
import gradio as gr
from huggingface_hub import InferenceClient

from ollama import Client
ollama.pull("llama3.2")
model = "llama3.2"

length = [750, 1000, 1500, 2000]
r_length = random.choice(length)
    
character = ["Man", "Woman", "Child", "Dog", "Cat"]
r_character = random.sample(character, 3)

time = ["15th century", "17th century", "19th century", "20th century", "21st century", "25th century"]
r_time = random.choice(time)

place = ["Asia", "Europe", "South America", "Africa", "Oceania", "North America"]
r_place = random.choice(place)

plot = "Events and actions that determine the story"

conflict = "The problems, struggles and successes encountered by the characters in the story"

theme = ["Literary Fiction", "Fantasy", "Sci-fi", "Mystery", "Horror"]
r_theme = random.choice(theme)

def chat_short_story(model, length, character, time, place, plot, conflict, theme):
    system_message = "You are a highly creative short story writer capable of writing across any genre"
    
    prompt = (f"Write a creative short story of {r_length} words, with characters: {', '.join(r_character)} "
              f"in {r_setting} with the following plot: {plot}. Include the {conflict} under the "
              f"theme of {r_theme}.")

    client = Client(host="http://localhost:11434")

    result = client.chat(model="llama3.2",  messages= [
    {
        "role": "assistant", "content": system_message,
        "role": "user", "content": prompt,
    },
  ])
  
    HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY")
    client = InferenceClient(api_key=HUGGINGFACE_API_KEY)
  
    story = ""

    if isinstance(result, list):
        for para in result:
            story += para
    else:
        story = result["message"]["content"]
    
    return story

story = chat_short_story(model, r_length, r_character, r_time, r_place, plot, conflict, r_theme)
display(story)

#Gradio setup
with gr.Blocks() as story-app:
  gr.Markdown(
    """
      AI Short Story Generator App
      This app takes in length of the story, theme and setting as user inputs and generates a short story between 750 and 2000 words. The 5 vital elements of a good short story
      namely characters, setting, plot, conflict, and theme are incorporated into every story generated by this app. Have fun!! :)
    """
  )
  input=[
  gr.Slider(value=100, label="Story Length", minimum=750, max=2000)
  gr.Dropdown(label="Time", choices=time)
  gr.Dropdown(label="Place", choices=placce)
  gr.Dropdown(label="Theme", choices=theme)
  ]
  output = gr.Textbox(label="The Story You Asked For")
  submit = gr.Button("Submit")
  submit.click(fn=chat_short_story, inputs=input, outputs=output)
  
story-app.launch()
